### ISSUE TITLE
Chicken Enemy must follow and shoot the player

### ISSUE THREAD

**Issue by marujalua** [MarcosChevis/alien-invaded#23]

**Comment by marujalua** [comment]
## Description
The enemies should follow the player and attack when it reaches the attack distance limit
## Taks
- [x] Create the Notification Service warning the enemies of the player position
- [x] Make the enemy follow the player
- [x] Make the enemy attack the player when it reach the attack minimum distance
- [x] Make a machine state that tell the enemy if it should follow the player

**Comment by MarcosChevis** [comment]
- [x] Padronize BitMasks
